### ISSUE TITLE
update README

### ISSUE THREAD

**Issue by An-GG** [effectiveaccelerationism/text-to-banger#26]
Current Install & Run instructions result in an error on my machine
<img width="803" alt="Screenshot 2023-08-16 at 2 10 46 PM" src="https://github.com/effectiveaccelerationism/text-to-banger/assets/20458990/2e1e81ce-f4d7-42cf-baca-1736674bf337">

Looks like something must have broke at some point.

Also, I would just like to interject for a moment and request that my previous pull request #10 be taken seriously, as it remains an open issue.

**Comment by codethazine** [comment]
Hey @An-GG, the README.md states that you need to `cd` into `webapp`, it looks like you're in root. I'll close the issue for now, let me know if that solves it
